INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the Toys", "Children", 800, "5/23/19", "7/03/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("ASPCA Dog Run", "Animals", 5000, "2/12/20", "3/1/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Race for the Cure", "Cancer Treatment", 10000, "8/3/19", "8/6/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Operation Christmas", "Children", 500, "11/29/19", "12/15/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Marks of Love", "Domestic Violence", 100, "4/5/19", "5/1/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the Center", "Community", 14500, "5/23/19", "6/30/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hungry for Houston", "Homeless", 2000, "1/5/20", "1/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Wounded Warriors", "Military", 250, "3/2/19", "5/15/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Voice of the Silent", "Human Trafficking", 5000, "9/14/19", "10/02/19");

INSERT INTO users (name, age) VALUES ("Bailee Williams", 36);
INSERT INTO users (name, age) VALUES ("Jacob Zeltman", 23);
INSERT INTO users (name, age) VALUES ("Megan Smith", 29);
INSERT INTO users (name, age) VALUES ("Patrick Fischl", 34);
INSERT INTO users (name, age) VALUES ("Stacy Franklin", 18);
INSERT INTO users (name, age) VALUES ("Jessica Bodine", 53);
INSERT INTO users (name, age) VALUES ("Michael Weirsma", 33);
INSERT INTO users (name, age) VALUES ("Taylor Reid", 22);
INSERT INTO users (name, age) VALUES ("Carie Anderson", 56);
INSERT INTO users (name, age) VALUES ("Janice Gruesbeck", 65);
INSERT INTO users (name, age) VALUES ("Mark Wagner", 44);
INSERT INTO users (name, age) VALUES ("George Kelley", 52);
INSERT INTO users (name, age) VALUES ("Daniel Elrich", 32);
INSERT INTO users (name, age) VALUES ("Alex Galvan", 25);
INSERT INTO users (name, age) VALUES ("", 27);
INSERT INTO users (name, age) VALUES ("Taylor Ulrich", 24);
INSERT INTO users (name, age) VALUES ("Kyle Ulrich", 31);
INSERT INTO users (name, age) VALUES ("Sean Pinnow", 32);
INSERT INTO users (name, age) VALUES ("Brady Ulrich", 19);
INSERT INTO users (name, age) VALUES ("Jaren Ulrich", 22);

INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 13, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 20, 1);
